/* ====================================================================
   JavaScript for ML Visualization Project
   ==================================================================== */

// Sample Data (Replace with real data from your Python analysis)
const sampleData = {
    correlations: {
        "prev_sem_gpa": 0.89,
        "study_hours_per_week": 0.67,
        "attendance_percentage": 0.58,
        "sleep_hours_per_day": 0.45,
        "english_proficiency_score": 0.42,
        "social_support_score": 0.38,
        "financial_support": 0.22,
        "family_income_usd": 0.18,
        "stress_level": -0.52,
        "work_hours_per_week": -0.35,
        "screen_time_hours": -0.28,
        "homesickness_level": -0.31
    },
    gpaStats: {
        mean: 2.52,
        median: 2.51,
        std: 0.43,
        min: 1.98,
        max: 3.98
    },
    modelPerformance: {
        "Gradient Boosting": { r2: 0.824, rmse: 0.312, mae: 0.189 },
        "Random Forest": { r2: 0.798, rmse: 0.356, mae: 0.234 },
        "CatBoost": { r2: 0.785, rmse: 0.378, mae: 0.251 },
        "Linear Regression": { r2: 0.654, rmse: 0.521, mae: 0.389 },
        "Ridge Regression": { r2: 0.651, rmse: 0.525, mae: 0.394 },
        "Lasso Regression": { r2: 0.628, rmse: 0.562, mae: 0.426 },
        "SVR": { r2: 0.612, rmse: 0.589, mae: 0.451 },
        "KNN": { r2: 0.598, rmse: 0.608, mae: 0.472 }
    },
    featureImportance: {
        "prev_sem_gpa": 0.285,
        "study_hours_per_week": 0.198,
        "attendance_percentage": 0.156,
        "english_proficiency_score": 0.089,
        "sleep_hours_per_day": 0.067,
        "stress_level": 0.062,
        "social_support_score": 0.051,
        "screen_time_hours": 0.041,
        "work_hours_per_week": 0.034,
        "family_income_usd": 0.018
    },
    profiles: {
        "high-performer": {
            name: "High Performer",
            prev_gpa: 3.8,
            study_hours: 35,
            attendance: 95,
            sleep_hours: 7,
            stress_level: 4,
            english_score: 110
        },
        "average-performer": {
            name: "Average Performer",
            prev_gpa: 2.8,
            study_hours: 20,
            attendance: 75,
            sleep_hours: 6,
            stress_level: 7,
            english_score: 85
        },
        "at-risk": {
            name: "At Risk",
            prev_gpa: 2.0,
            study_hours: 8,
            attendance: 50,
            sleep_hours: 5,
            stress_level: 9,
            english_score: 70
        }
    }
};

// ====================================================================
// UTILITY FUNCTIONS
// ====================================================================

function updateSliderValue(inputId, displayId, unit = '') {
    const input = document.getElementById(inputId);
    const display = document.getElementById(displayId);
    
    if (input && display) {
        input.addEventListener('input', (e) => {
            display.textContent = e.target.value + unit;
        });
    }
}

function setupSliders() {
    updateSliderValue('prev-gpa', 'prev-gpa-value');
    updateSliderValue('study-hours', 'study-hours-value', ' hours');
    updateSliderValue('attendance', 'attendance-value', '%');
    updateSliderValue('sleep-hours', 'sleep-hours-value', ' hours');
    updateSliderValue('stress-level', 'stress-level-value');
    updateSliderValue('english-score', 'english-score-value');
}

// ====================================================================
// VISUALIZATION FUNCTIONS
// ====================================================================

// Attempt to load real JSON data generated by `generate_viz_data.py` if present
function loadDataFromJSON() {
    const promises = [];
    const map = {
        'data/correlations.json': 'correlations',
        'data/distributions.json': 'distributions',
        'data/model_performance.json': 'modelPerformance',
        'data/best_model_info.json': 'bestModelInfo',
        'data/sample_profiles.json': 'profiles',
        'data/basic_stats.json': 'basicStats',
        'data/points.json': 'points',
        'data/embeddings.json': 'embeddings',
        'data/shap_summary.json': 'shap'
    };

    Object.keys(map).forEach(path => {
        const key = map[path];
        const p = fetch(path).then(r => {
            if (!r.ok) throw new Error('not found');
            return r.json();
        }).then(json => {
            try {
                if (key === 'correlations') {
                    // correlations.json structure: { gpa_correlations: {...}, ... }
                    if (json.gpa_correlations) sampleData.correlations = json.gpa_correlations;
                } else if (key === 'distributions') {
                    sampleData.gpaStats = json.semester_gpa || sampleData.gpaStats;
                } else if (key === 'modelPerformance') {
                    // expect an array of {name, r2_test, rmse_test, cv_r2_mean}
                    const perf = {};
                    json.forEach(item => { perf[item.name] = {r2: item.r2_test || item.r2, rmse: item.rmse_test || item.rmse}; });
                    sampleData.modelPerformance = perf;
                } else if (key === 'bestModelInfo') {
                    if (json.feature_importance) sampleData.featureImportance = json.feature_importance;
                } else if (key === 'profiles') {
                    // profiles JSON is an array of profiles
                    const obj = {};
                    if (Array.isArray(json)) {
                        json.forEach(p => {
                            const id = p.name.toLowerCase().replace(/\s+/g, '-');
                            obj[id] = {
                                name: p.name,
                                prev_gpa: p.profile.prev_sem_gpa || p.profile.prev_gpa || 2.5,
                                study_hours: p.profile.study_hours_per_week || p.profile.study_hours || 20,
                                attendance: p.profile.attendance_percentage || p.profile.attendance || 75,
                                sleep_hours: p.profile.sleep_hours_per_day || p.profile.sleep_hours || 6,
                                stress_level: p.profile.stress_level || 5,
                                english_score: p.profile.english_proficiency_score || p.profile.english_score || 85
                            };
                        });
                        sampleData.profiles = obj;
                    }
                } else if (key === 'points') {
                    if (json.points) {
                        sampleData.points = json.points;
                        if (json.numeric_features) sampleData.numeric_features = json.numeric_features;
                    }
                } else if (key === 'embeddings') {
                    if (json.embeddings) sampleData.embeddings = json.embeddings;
                } else if (key === 'shap') {
                    if (json.shap_summary) sampleData.shap_summary = json.shap_summary;
                } else if (key === 'basicStats') {
                    if (json.total_records) sampleData.basicStats = json;
                }
            } catch (e) {
                console.warn('Error applying JSON:', path, e);
            }
        }).catch(() => { /* file not present -> keep sample data */ });

        promises.push(p);
    });

    return Promise.all(promises);
}


function createCorrelationChart() {
    // D3 horizontal bar chart for correlations
    const container = document.getElementById('correlation-chart');
    if (!container) return;
    container.innerHTML = '';

    const data = Object.entries(sampleData.correlations).map(([k, v]) => ({key: k, value: v}));
    data.sort((a, b) => b.value - a.value);

    const margin = {top: 24, right: 20, bottom: 30, left: 220};
    const width = Math.max(600, container.clientWidth) - margin.left - margin.right;
    const height = Math.min(500, data.length * 32) - margin.top - margin.bottom;

    const svg = d3.select(container)
        .append('svg')
        .attr('width', width + margin.left + margin.right)
        .attr('height', height + margin.top + margin.bottom)
        .attr('viewBox', `0 0 ${width + margin.left + margin.right} ${height + margin.top + margin.bottom}`)
        .style('background', '#ffffff');

    const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);

    const x = d3.scaleLinear()
        .domain([d3.min(data, d => Math.min(-1, d.value)), d3.max(data, d => Math.max(1, d.value))])
        .range([0, width]);

    const y = d3.scaleBand()
        .domain(data.map(d => d.key))
        .range([0, height])
        .padding(0.15);

    // Axis
    g.append('g').call(d3.axisLeft(y).tickFormat(d => d.replace(/_/g, ' '))).selectAll('text').style('font-family', 'system-ui');

    g.append('g')
        .attr('transform', `translate(0,${height})`)
        .call(d3.axisBottom(x).ticks(6));

    // Zero line
    g.append('line')
        .attr('x1', x(0))
        .attr('x2', x(0))
        .attr('y1', 0)
        .attr('y2', height)
        .attr('stroke', '#ddd')
        .attr('stroke-width', 1);

    // Bars
    g.selectAll('.bar')
        .data(data)
        .enter()
        .append('rect')
        .attr('class', 'bar')
        .attr('y', d => y(d.key))
        .attr('height', y.bandwidth())
        .attr('x', d => x(Math.min(0, d.value)))
        .attr('width', d => Math.abs(x(d.value) - x(0)))
        .attr('fill', d => d.value >= 0 ? '#10b981' : '#ef4444')
        .attr('rx', 4)
        .attr('ry', 4);

    // Labels
    g.selectAll('.label')
        .data(data)
        .enter()
        .append('text')
        .attr('class', 'label')
        .attr('x', d => d.value >= 0 ? x(d.value) + 6 : x(d.value) - 6)
        .attr('y', d => y(d.key) + y.bandwidth() / 2)
        .attr('dy', '0.35em')
        .attr('text-anchor', d => d.value >= 0 ? 'start' : 'end')
        .text(d => d.value.toFixed(2))
        .style('font-family', 'system-ui')
        .style('font-weight', 700)
        .style('fill', '#1e293b');
}

function createDistributionChart() {
    // D3 histogram for GPA distribution
    const container = document.getElementById('distribution-chart');
    if (!container) return;
    container.innerHTML = '';

    // Create synthetic sample using stats if raw sample not available
    const n = 500;
    const mean = sampleData.gpaStats.mean;
    const std = sampleData.gpaStats.std;
    const values = d3.range(n).map(() => d3.randomNormal(mean, std)());

    const margin = {top: 24, right: 20, bottom: 30, left: 40};
    const width = Math.max(480, container.clientWidth) - margin.left - margin.right;
    const height = 360 - margin.top - margin.bottom;

    const svg = d3.select(container)
        .append('svg')
        .attr('width', width + margin.left + margin.right)
        .attr('height', height + margin.top + margin.bottom)
        .attr('viewBox', `0 0 ${width + margin.left + margin.right} ${height + margin.top + margin.bottom}`)
        .style('background', '#ffffff');

    const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);

    const x = d3.scaleLinear().domain([Math.min(...values), Math.max(...values)]).nice().range([0, width]);
    const bins = d3.bin().domain(x.domain()).thresholds(30)(values);
    const y = d3.scaleLinear().domain([0, d3.max(bins, d => d.length)]).nice().range([height, 0]);

    g.append('g')
        .selectAll('rect')
        .data(bins)
        .enter().append('rect')
        .attr('x', d => x(d.x0) + 1)
        .attr('y', d => y(d.length))
        .attr('width', d => Math.max(0, x(d.x1) - x(d.x0) - 1))
        .attr('height', d => height - y(d.length))
        .attr('fill', '#2563eb')
        .attr('opacity', 0.9);

    g.append('g').attr('transform', `translate(0,${height})`).call(d3.axisBottom(x));
    g.append('g').call(d3.axisLeft(y));

    // Title
    svg.append('text')
        .attr('x', (width + margin.left + margin.right) / 2)
        .attr('y', margin.top / 2)
        .attr('text-anchor', 'middle')
        .style('font-size', '16px')
        .style('font-weight', '700')
        .text('Semester GPA Distribution');
}

// -----------------------------
// Filtering & Embedding helpers
// -----------------------------
function setupFilters() {
    const genderSelect = document.getElementById('filter-gender');
    const countrySelect = document.getElementById('filter-country');
    const resetBtn = document.getElementById('filter-reset');

    if (!sampleData.points) return;

    const genders = Array.from(new Set(sampleData.points.map(p => p.gender).filter(Boolean))).sort();
    const countries = Array.from(new Set(sampleData.points.map(p => p.country_region).filter(Boolean))).sort();

    if (genderSelect) {
        genders.forEach(g => { const opt = document.createElement('option'); opt.value = g; opt.textContent = g; genderSelect.appendChild(opt); });
        genderSelect.addEventListener('change', applyFilters);
    }
    if (countrySelect) {
        countries.forEach(c => { const opt = document.createElement('option'); opt.value = c; opt.textContent = c; countrySelect.appendChild(opt); });
        countrySelect.addEventListener('change', applyFilters);
    }
    if (resetBtn) resetBtn.addEventListener('click', () => { if (genderSelect) genderSelect.value = 'all'; if (countrySelect) countrySelect.value = 'all'; applyFilters(); });
    // initial apply
    applyFilters();
}

function applyFilters() {
    if (!sampleData.points) return;
    const gender = document.getElementById('filter-gender') ? document.getElementById('filter-gender').value : 'all';
    const country = document.getElementById('filter-country') ? document.getElementById('filter-country').value : 'all';

    let filtered = sampleData.points;
    if (gender && gender !== 'all') filtered = filtered.filter(p => p.gender === gender);
    if (country && country !== 'all') filtered = filtered.filter(p => p.country_region === country);

    sampleData._filteredIds = new Set(filtered.map(p => p.id));
    computeCorrelationsFromPoints(filtered);
    createDistributionChart();
    updateEmbeddingSelection();
}

function computeCorrelationsFromPoints(points) {
    if (!points || points.length === 0) return;
    const numeric = sampleData.numeric_features || Object.keys(sampleData.featureImportance);
    const corr = {};
    function mean(arr) { return arr.reduce((a,b)=>a+b,0)/arr.length; }
    function pearson(xs, ys) {
        const xm = mean(xs), ym = mean(ys);
        const num = xs.reduce((s,xi,i)=>s + (xi - xm)*(ys[i]-ym), 0);
        const den = Math.sqrt(xs.reduce((s,xi)=>s+(xi-xm)*(xi-xm),0) * ys.reduce((s,yi)=>s+(yi-ym)*(yi-ym),0));
        return den === 0 ? 0 : num/den;
    }
    numeric.forEach(f => {
        const pairs = points.map(p => ({x: p.semester_gpa, y: p[f]})).filter(d=>d.x!=null && d.y!=null);
        if (pairs.length < 4) { corr[f] = 0; return; }
        const xs = pairs.map(d=>d.x), ys = pairs.map(d=>d.y);
        corr[f] = pearson(xs, ys);
    });
    sampleData.correlations = corr;
    populateFactorsLists();
    createCorrelationChart();
}

let _embedding_svg = null;
function createEmbeddingPlot() {
    const container = document.getElementById('embedding-plot');
    if (!container || !sampleData.points) return;
    container.innerHTML = '';
    const use = (sampleData.embeddings && sampleData.embeddings.umap) ? 'umap' : ((sampleData.embeddings && sampleData.embeddings.tsne) ? 'tsne' : null);
    const xKey = use === 'umap' ? 'umap_x' : 'tsne_x';
    const yKey = use === 'umap' ? 'umap_y' : 'tsne_y';
    if (!use) { container.innerHTML = '<p>No embeddings available. Run `generate_viz_data.py` to create embeddings.</p>'; return; }
    const pts = sampleData.points.filter(p => p[xKey] != null && p[yKey] != null);
    const margin = {top: 10, right: 10, bottom: 40, left: 40};
    const width = Math.max(520, container.clientWidth) - margin.left - margin.right;
    const height = 420 - margin.top - margin.bottom;
    const svg = d3.select(container).append('svg').attr('width', width + margin.left + margin.right).attr('height', height + margin.top + margin.bottom).attr('viewBox', `0 0 ${width + margin.left + margin.right} ${height + margin.top + margin.bottom}`).style('background', '#fff');
    _embedding_svg = svg;
    const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);
    const x = d3.scaleLinear().domain(d3.extent(pts, d => d[xKey])).range([0, width]).nice();
    const y = d3.scaleLinear().domain(d3.extent(pts, d => d[yKey])).range([height, 0]).nice();
    const color = d3.scaleSequential(d3.interpolateTurbo).domain(d3.extent(pts, d => d.semester_gpa));
    g.append('g').attr('transform', `translate(0,${height})`).call(d3.axisBottom(x));
    g.append('g').call(d3.axisLeft(y));
    g.selectAll('.dot').data(pts).enter().append('circle').attr('class', 'dot').attr('cx', d => x(d[xKey])).attr('cy', d => y(d[yKey])).attr('r', 4).attr('fill', d => color(d.semester_gpa)).attr('fill-opacity', 0.85).attr('stroke', '#111').attr('stroke-opacity', 0.05).attr('data-id', d => d.id);
    const brush = d3.brush().extent([[0,0],[width,height]]).on('end', (event) => {
        if (!event.selection) { sampleData._selectedIds = new Set(); updateEmbeddingSelection(); return; }
        const [[x0,y0],[x1,y1]] = event.selection;
        const selected = pts.filter(d => { const sx = x(d[xKey]), sy = y(d[yKey]); return sx >= x0 && sx <= x1 && sy >= y0 && sy <= y1; }).map(d => d.id);
        sampleData._selectedIds = new Set(selected);
        updateEmbeddingSelection();
    });
    g.append('g').call(brush);
    svg.append('text').attr('x', margin.left + 8).attr('y', 14).text(use.toUpperCase() + ' embedding').style('font-weight',700);
    sampleData._selectedIds = new Set();
}

function updateEmbeddingSelection() {
    if (!_embedding_svg) return;
    const svg = _embedding_svg;
    const selected = sampleData._selectedIds || new Set();
    svg.selectAll('.dot').attr('fill-opacity', function() { const id = +this.getAttribute('data-id'); if (selected.size === 0) return 0.85; return selected.has(id) ? 1.0 : 0.12; });
    createDistributionChart();
}

function createModelPerformanceCharts() {
    // Simple D3 bar charts for R2 and RMSE
    const r2Container = document.getElementById('r2-chart');
    const rmseContainer = document.getElementById('rmse-chart');
    if (r2Container) {
        r2Container.innerHTML = '';
        const models = Object.keys(sampleData.modelPerformance);
        const data = models.map(m => ({name: m, value: sampleData.modelPerformance[m].r2}));
        drawVerticalBarChart(r2Container, data, {title: 'R² Score Comparison', yLabel: 'R² Score', maxY: 1});
    }
    if (rmseContainer) {
        rmseContainer.innerHTML = '';
        const models = Object.keys(sampleData.modelPerformance);
        const data = models.map(m => ({name: m, value: sampleData.modelPerformance[m].rmse}));
        drawVerticalBarChart(rmseContainer, data, {title: 'RMSE Comparison', yLabel: 'RMSE (lower better)'});
    }
}

function drawVerticalBarChart(container, data, opts = {}) {
    const margin = {top: 40, right: 10, bottom: 80, left: 50};
    const width = Math.max(420, container.clientWidth) - margin.left - margin.right;
    const height = 360 - margin.top - margin.bottom;

    const svg = d3.select(container).append('svg')
        .attr('width', width + margin.left + margin.right)
        .attr('height', height + margin.top + margin.bottom)
        .attr('viewBox', `0 0 ${width + margin.left + margin.right} ${height + margin.top + margin.bottom}`)
        .style('background', '#ffffff');

    const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);

    const x = d3.scaleBand().domain(data.map(d => d.name)).range([0, width]).padding(0.2);
    const yMax = opts.maxY !== undefined ? opts.maxY : d3.max(data, d => d.value) * 1.1;
    const y = d3.scaleLinear().domain([0, yMax]).range([height, 0]).nice();

    g.append('g').attr('transform', `translate(0,${height})`).call(d3.axisBottom(x)).selectAll('text')
        .attr('transform', 'rotate(-35)')
        .style('text-anchor', 'end');

    g.append('g').call(d3.axisLeft(y));

    g.selectAll('.bar')
        .data(data)
        .enter()
        .append('rect')
        .attr('class', 'bar')
        .attr('x', d => x(d.name))
        .attr('y', d => y(d.value))
        .attr('width', x.bandwidth())
        .attr('height', d => height - y(d.value))
        .attr('fill', d => {
            if (opts.yLabel && opts.yLabel.toLowerCase().includes('r²')) return d.value > 0.8 ? '#10b981' : d.value > 0.7 ? '#f59e0b' : '#ef4444';
            return d.value < 0.4 ? '#10b981' : d.value < 0.6 ? '#f59e0b' : '#ef4444';
        });

    // Title
    svg.append('text')
        .attr('x', (width + margin.left + margin.right) / 2)
        .attr('y', margin.top / 2)
        .attr('text-anchor', 'middle')
        .style('font-size', '16px')
        .style('font-weight', '700')
        .text(opts.title || '');
}

function createFeatureImportanceChart() {
    const container = document.getElementById('feature-importance');
    if (!container) return;
    container.innerHTML = '';

    const data = Object.entries(sampleData.featureImportance).map(([k,v]) => ({key: k, value: v}));
    data.sort((a,b) => b.value - a.value);
    const top = data.slice(0, 10);

    const margin = {top: 24, right: 20, bottom: 30, left: 180};
    const width = Math.max(520, container.clientWidth) - margin.left - margin.right;
    const height = Math.min(360, top.length * 32) - margin.top - margin.bottom;

    const svg = d3.select(container)
        .append('svg')
        .attr('width', width + margin.left + margin.right)
        .attr('height', height + margin.top + margin.bottom)
        .attr('viewBox', `0 0 ${width + margin.left + margin.right} ${height + margin.top + margin.bottom}`)
        .style('background', '#ffffff');

    const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);

    const x = d3.scaleLinear().domain([0, d3.max(top, d => d.value)]).range([0, width]).nice();
    const y = d3.scaleBand().domain(top.map(d => d.key)).range([0, height]).padding(0.15);

    g.append('g').call(d3.axisLeft(y).tickFormat(d => d.replace(/_/g, ' '))).selectAll('text').style('font-family', 'system-ui');
    g.append('g').attr('transform', `translate(0,${height})`).call(d3.axisBottom(x));

    g.selectAll('.bar')
        .data(top)
        .enter()
        .append('rect')
        .attr('y', d => y(d.key))
        .attr('height', y.bandwidth())
        .attr('x', 0)
        .attr('width', d => x(d.value))
        .attr('fill', '#2563eb')
        .attr('rx', 4);

    g.selectAll('.label')
        .data(top)
        .enter()
        .append('text')
        .attr('x', d => x(d.value) + 6)
        .attr('y', d => y(d.key) + y.bandwidth()/2)
        .attr('dy', '0.35em')
        .text(d => d.value.toFixed(3))
        .style('font-weight', 700)
        .style('fill', '#1e293b');
}

function populateFactorsLists() {
    const positiveFactors = Object.entries(sampleData.correlations)
        .filter(([_, val]) => val > 0.3)
        .sort((a, b) => b[1] - a[1]);
    
    const negativeFactors = Object.entries(sampleData.correlations)
        .filter(([_, val]) => val < -0.2)
        .sort((a, b) => a[1] - b[1]);
    
    const positiveList = document.getElementById('positive-factors');
    if (positiveList) {
        positiveList.innerHTML = positiveFactors.map(([key, val]) => `
            <div class="factor-item">
                <strong>${key.replace(/_/g, ' ')}</strong>
                <span class="factor-correlation">r = ${val.toFixed(2)}</span>
            </div>
        `).join('');
    }
    
    const negativeList = document.getElementById('negative-factors');
    if (negativeList) {
        negativeList.innerHTML = negativeFactors.map(([key, val]) => `
            <div class="factor-item">
                <strong>${key.replace(/_/g, ' ')}</strong>
                <span class="factor-correlation">r = ${val.toFixed(2)}</span>
            </div>
        `).join('');
    }
}

// ====================================================================
// PREDICTION LOGIC
// ====================================================================

function predictGPA(prevGPA, studyHours, attendance, sleepHours, stressLevel, englishScore) {
    // Simplified prediction model based on correlations
    const baseGPA = 2.52; // mean GPA
    
    // Normalize inputs (0-1 scale)
    const normPrevGPA = (prevGPA / 4.0) * 0.89; // correlation 0.89
    const normStudyHours = Math.min(studyHours / 50, 1.0) * 0.67; // correlation 0.67
    const normAttendance = (attendance / 100) * 0.58; // correlation 0.58
    const normSleepHours = Math.min(sleepHours / 10, 1.0) * 0.45; // correlation 0.45
    const normStress = (1 - stressLevel / 10) * 0.52; // negative correlation
    const normEnglish = Math.min(englishScore / 120, 1.0) * 0.42; // correlation 0.42
    
    // Weighted sum
    const prediction = baseGPA + 
        (normPrevGPA * 0.4) +
        (normStudyHours * 0.25) +
        (normAttendance * 0.15) +
        (normSleepHours * 0.08) +
        (normStress * 0.07) +
        (normEnglish * 0.05);
    
    // Clamp to reasonable range
    return Math.max(1.5, Math.min(4.0, prediction));
}

function handlePrediction() {
    const prevGPA = parseFloat(document.getElementById('prev-gpa').value);
    const studyHours = parseInt(document.getElementById('study-hours').value);
    const attendance = parseInt(document.getElementById('attendance').value);
    const sleepHours = parseFloat(document.getElementById('sleep-hours').value);
    const stressLevel = parseInt(document.getElementById('stress-level').value);
    const englishScore = parseInt(document.getElementById('english-score').value);
    
    const predicted = predictGPA(prevGPA, studyHours, attendance, sleepHours, stressLevel, englishScore);
    
    // Update result display
    document.getElementById('result-placeholder').classList.add('hidden');
    const resultBox = document.getElementById('prediction-result');
    resultBox.classList.remove('hidden');
    
    document.getElementById('predicted-gpa').textContent = predicted.toFixed(2);
    document.getElementById('comp-prediction').textContent = predicted.toFixed(2);
    document.getElementById('comp-diff').textContent = (predicted - 2.52).toFixed(2);
    
    // Generate interpretation
    const interpretation = getInterpretation(predicted, prevGPA, studyHours, stressLevel);
    document.getElementById('result-text').textContent = interpretation;
}

function getInterpretation(gpa, prevGPA, studyHours, stress) {
    let text = '';
    
    if (gpa > 3.5) {
        text = `Excellent! Predicted GPA of ${gpa.toFixed(2)} suggests strong academic performance. `;
    } else if (gpa > 3.0) {
        text = `Good! Predicted GPA of ${gpa.toFixed(2)} indicates solid academic standing. `;
    } else if (gpa > 2.5) {
        text = `Moderate. Predicted GPA of ${gpa.toFixed(2)} is close to the average. `;
    } else {
        text = `At Risk. Predicted GPA of ${gpa.toFixed(2)} suggests challenges ahead. `;
    }
    
    if (studyHours < 15) {
        text += 'Increasing study hours could significantly improve your GPA. ';
    }
    
    if (stress > 7) {
        text += 'High stress levels are negatively impacting your academic performance. Consider stress management strategies. ';
    }
    
    if (prevGPA < 2.0) {
        text += 'Your previous semester GPA is a strong predictor - focused improvement efforts could help turn things around.';
    }
    
    return text;
}

function loadProfile(profileKey) {
    const profile = sampleData.profiles[profileKey];
    if (!profile) return;
    
    document.getElementById('prev-gpa').value = profile.prev_gpa;
    document.getElementById('study-hours').value = profile.study_hours;
    document.getElementById('attendance').value = profile.attendance;
    document.getElementById('sleep-hours').value = profile.sleep_hours;
    document.getElementById('stress-level').value = profile.stress_level;
    document.getElementById('english-score').value = profile.english_score;
    
    // Update all slider displays
    document.getElementById('prev-gpa-value').textContent = profile.prev_gpa;
    document.getElementById('study-hours-value').textContent = profile.study_hours + ' hours';
    document.getElementById('attendance-value').textContent = profile.attendance + '%';
    document.getElementById('sleep-hours-value').textContent = profile.sleep_hours + ' hours';
    document.getElementById('stress-level-value').textContent = profile.stress_level;
    document.getElementById('english-score-value').textContent = profile.english_score;
    
    // Auto-predict
    handlePrediction();
}

// ====================================================================
// EVENT LISTENERS
// ====================================================================

document.addEventListener('DOMContentLoaded', function() {
    // Setup sliders
    setupSliders();
    
    // Load real data if available, then create charts. Falls back to sampleData.
    loadDataFromJSON().finally(() => {
        createCorrelationChart();
        createDistributionChart();
        createModelPerformanceCharts();
        createFeatureImportanceChart();
        createSHAPChart();
        populateFactorsLists();

        function createSHAPChart() {
            const container = document.getElementById('shap-summary');
            if (!container) return;
            container.innerHTML = '';
            if (!sampleData.shap_summary) {
                container.innerHTML = '<p class="muted">No SHAP summary found. Run `generate_viz_data.py` with the `shap` package installed to generate SHAP summaries.</p>';
                return;
            }

            const entries = Object.entries(sampleData.shap_summary).map(([k,v]) => ({key: k, value: v}));
            entries.sort((a,b)=>b.value - a.value);
            const top = entries.slice(0,10);

            const margin = {top: 24, right: 20, bottom: 30, left: 180};
            const width = Math.max(520, container.clientWidth) - margin.left - margin.right;
            const height = Math.min(360, top.length * 32) - margin.top - margin.bottom;

            const svg = d3.select(container)
                .append('svg')
                .attr('width', width + margin.left + margin.right)
                .attr('height', height + margin.top + margin.bottom)
                .attr('viewBox', `0 0 ${width + margin.left + margin.right} ${height + margin.top + margin.bottom}`)
                .style('background', '#ffffff');

            const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);
            const x = d3.scaleLinear().domain([0, d3.max(top, d=>d.value)]).range([0,width]).nice();
            const y = d3.scaleBand().domain(top.map(d=>d.key)).range([0,height]).padding(0.15);
            g.append('g').call(d3.axisLeft(y).tickFormat(d=>d.replace(/_/g,' '))).selectAll('text').style('font-family','system-ui');
            g.append('g').attr('transform', `translate(0,${height})`).call(d3.axisBottom(x));
            g.selectAll('.bar').data(top).enter().append('rect').attr('y', d=>y(d.key)).attr('height', y.bandwidth()).attr('x', 0).attr('width', d=>x(d.value)).attr('fill','#7c3aed').attr('rx',4);
            g.selectAll('.label').data(top).enter().append('text').attr('x', d=>x(d.value)+6).attr('y', d=>y(d.key)+y.bandwidth()/2).attr('dy','0.35em').text(d=>d.value.toFixed(3)).style('font-weight',700).style('fill','#1e293b');
        }
        // If point-level data present, setup filters and embedding
        setupFilters();
        createEmbeddingPlot();
    });
    
    // Prediction button
    const predictBtn = document.getElementById('predict-btn');
    if (predictBtn) {
        predictBtn.addEventListener('click', handlePrediction);
    }
    
    // Profile buttons
    document.querySelectorAll('.profile-btn').forEach(btn => {
        btn.addEventListener('click', (e) => {
            const profileKey = e.currentTarget.getAttribute('data-profile');
            loadProfile(profileKey);
        });
    });
    
    // Smooth scroll for nav links
    document.querySelectorAll('.nav-link').forEach(link => {
        link.addEventListener('click', (e) => {
            const href = link.getAttribute('href');
            if (href.startsWith('#')) {
                e.preventDefault();
                const target = document.querySelector(href);
                if (target) {
                    target.scrollIntoView({ behavior: 'smooth' });
                }
            }
        });
    });
    
    console.log('✅ Visualization dashboard loaded successfully!');
});

// Add some style for factors items
const style = document.createElement('style');
style.textContent = `
.factor-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.75rem;
    margin-bottom: 0.75rem;
    background: white;
    border-radius: 8px;
    border-left: 4px solid #2563eb;
}

.factor-correlation {
    background: #f0f9ff;
    padding: 0.25rem 0.75rem;
    border-radius: 12px;
    font-weight: 700;
    color: #2563eb;
    font-size: 0.85rem;
}
`;
document.head.appendChild(style);
